name: dolbyio_getting_started
description: A new Flutter project.

publish_to: 'none'

version: 3.6.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dolbyio_comms_sdk_flutter: 
    path: ../
  permission_handler: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
